CREATE TABLE users(

    id INT AUTO_INCREMENT PRIMARY KEY,

    name VARCHAR(100) NOT NULL,

    email VARCHAR(150) UNIQUE NOT NULL,

    password VARCHAR(255) NOT NULL,

    role VARCHAR(50) DEFAULT 'admin',

    remember_token VARCHAR(255),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);